<?php

/**
 * Implements hook_block_info().
 */
function hello_world_block_info() {
  $blocks['hello_world'] = array(
    // The name that will appear in the block list.
    'info' => t('Hello World'),
    'status' => TRUE,
    'region' => 'sidebar_second'
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hello_world_block_view($delta = '') {
  $block = array();
  $block['subject'] = t('Hello World!');

  $result = hello_world_contents();

  // Array to contain items for the block to render.
  $items = array();

  // Iterate over the results and format as links.
  foreach ($result as $node) {
    $items[] = array(
      'data' => l($node->title, 'node/' . $node->nid),
    );
  }

  // No content of type Hello World Article.
  if (empty($items)) {
    $block['content'] = t('No Hello World articles available.');
  } else {
    // Pass data through theme function.
    $block['content'] = theme('item_list', array(
      'items' => $items)
    );
  }
  return $block;
}

/**
 * Custom content function.
 *
 * Retrieve Hello World Article nodes tagged with enabled terms of the Sections
 * vocabulary
 *
 * @return array
 *   A result set of nodes.
 */
function hello_world_contents() {

  $query = db_select('node', 'n');
  $query->join('taxonomy_index', 'i', 'i.nid=n.nid');
  $query->join('taxonomy_term_data', 't', 'i.tid=t.tid');
  $query->join('taxonomy_vocabulary', 'v', 'v.vid=t.vid');
  $query->join('field_data_field_enabled', 'e', 'e.entity_id=i.tid');
  $query->fields('n', array('nid', 'title'));
  $query->condition('status', 1);
  $query->condition('type', 'hello_world_article');
  $query->condition('field_enabled_value', 1);
  $query->condition('v.name', 'Sections');

  $result = $query->execute();
  return $result;
}

/**
 * Implements hook_page_alter().
 */
function hello_world_page_alter(&$page) {

  if (isset($page['content']['system_main']['nodes'])) {
    foreach ($page['content']['system_main']['nodes'] as $nid => $nodes) {
      $bundle = $page['content']['system_main']['nodes'][$nid]['#bundle'];
      $view_mode = $page['content']['system_main']['nodes'][$nid]['#view_mode'];

      if ($bundle == 'hello_world_article' and $view_mode == 'full') {
        $page['content']['system_main']['hello_world'] = array(
          '#type' => 'markup',
          '#markup' => t('Content starts here!'),
          '#id' => 'hello-world-message',
          '#weight' => -20,
          '#prefix' => '<div class="hello-world-message">',
          '#suffix' => '</div>',
        );
      }
    }
  }
}
