<?php

/**
 * Implements hook_block_info().
 */
function hello_world_block_info() {
  $blocks['hello_world'] = array(
    // The name that will appear in the block list.
    'info' => t('Hello World'),
    'status' => TRUE,
    'region' => 'sidebar_second'
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hello_world_block_view($delta = '') {
  $block = array();
  $block['subject'] = t('Hello World!');

  $result = hello_world_contents();

  // Array to contain items for the block to render.
  $items = array();

  // Iterate over the resultset and format as links.
  foreach ($result as $node) {
    $items[] = array(
      'data' => l($node->title, 'node/' . $node->nid),
    );
  }

  // No content of type Hello World Article.
  if (empty($items)) {
    $block['content'] = t('No Hello World articles available.');
  } else {
    // Pass data through theme function.
    $block['content'] = theme('item_list', array(
      'items' => $items)
    );
  }
  return $block;
}

/**
 * Custom content function.
 *
 * Retrieve Hello World Article nodes
 *
 * @return
 *   A result set of nodes.
 */
function hello_world_contents() {
  //Use Database API to retrieve Hello World Article nodes.
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('status', 1)
    ->condition('type', 'hello_world_article')
    ->execute();
  return $query;
}
